#!/usr/bin/env node
var isPRArg = process.argv[2] && process.argv[2].split("=");
var isPR = isPRArg && isPRArg[0] === "isPR" && isPRArg[1] === "true";
require('./')(isPR, process.cwd(), function(error, missing) {
  if (error) {
    console.error(error)
    process.exit(1) }
  else if (missing.length > 0) {
    missing.forEach(function(name) {
      process.stderr.write( 'Missing AUTHORS line for "' + name + '"\n') })
    process.exit(1) }
  else {
    process.stdout.write('All Git commit authors are listed in AUTHORS\n')
    process.exit(0) } })
